/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
// @ts-ignore
import * as avatar from 'assets/avatar.gltf';

export default function Model(props: object) {
  const group = useRef()
  // @ts-ignore
  // const { nodes, materials } = useGLTF('/avatar.gltf')
  console.log(avatar);
  // @ts-ignore
  const { nodes, materials } = useGLTF(avatar.default)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.DefaultMaterial} geometry={nodes.Mesh.geometry} />
    </group>
  )
}

// useGLTF.preload('/avatar.gltf')
useGLTF.preload(avatar.default)
